default:
  adapter: sqlite3
  database: db/development.sqlite3
  username: user
  password: password
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  username: user
  password: password
  host: localhost

production:
  adapter: sqlite3
  database: db/production.sqlite3
  username: user
  password: password
  host: localhost
